myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls',namespace='shop')),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "Q-Tec Admin"
admin.site.site_title = "Q-Tec Admin Portal"
admin.site.index_title = "Q-Tec Researcher Portal"

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.CategoryListView.as_view(), name="category_list"),
    path('<int:pk>/', views.CategoryProductView.as_view(), name="category_product"),
    path('ajax/search-and-filter/', views.load_search_and_filter, name="ajax_load_search_and_filter"),
    
]

shop/models.py
from django.db import models

# Create your models here.

class GenericFilter(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class GenericFilterValues(models.Model):
    category = models.ForeignKey(GenericFilter, on_delete=models.CASCADE, related_name="generic_filter") 
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="category")

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")

    def __str__(self):
        return self.name
    
class ProductFilter(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(GenericFilter, on_delete=models.CASCADE)
    value = models.ForeignKey(GenericFilterValues, on_delete=models.CASCADE)

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View 
from .models import GenericFilter,ProductFilter, Product,  Category
from django.views.generic import ListView

# Create your views here.


class CategoryListView(ListView):
    model = Category
    template_name = "shop/home.html"


class CategoryProductView(View):
    def get(self, request, pk):
        category = get_object_or_404(Category, id=pk)
        products = Product.objects.filter(category__id = pk)
        product_filter = GenericFilter.objects.all()
        min_price = min(products.values_list('price'))[0]
        max_price = max(products.values_list('price'))[0]
        context = {
            'category': category,
            'products':products,
            'count': products.count(),
            'min_price': min_price,
            'max_price': max_price,
            'product_filter' : product_filter
        }
        return render(request, "shop/category_products.html", context)
   


def load_search_and_filter(request):
    price_range = request.GET.getlist('price_range[]')
    filter_value_list = request.GET.getlist('filter_value_list[]')
    category_id = request.GET.getlist('category_id')[0]
    category = get_object_or_404(Category, id=category_id)
    if filter_value_list:
        products = Product.objects.filter(category__id = category_id, price__range=(price_range[0],price_range[1]), productfilter__value__id__in = filter_value_list).distinct()
    elif price_range:
        products = Product.objects.filter(category__id = category_id, price__range=(price_range[0],price_range[1]))
    else:
        products = Product.objects.filter(category__id = category_id)
    return render(request, 'partials/filter.html', {'products':products, 'category': category, 'count': products.count()})

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <title>Hello, world!</title>
  </head>
  <body>
    <!-- main content -->
    {% block content %}

    {% endblock content %}
    <!-- end of main content -->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/partials/css.html
<style type="text/css">
    body{
    background:#eee;
    }
    
    .row {
        margin-right: 0px;
        margin-left: 0px;
    }

    </style>

templates/partials/filter.html
{% load static %}

<h1 class="p-2">{{category}} has {{count}} Products</h1>
<div class="row row-cols-1 row-cols-md-4 g-4">

    {% for product in products %}
    <div class="col">
      <div class="card">
        <img src="{% static 'product1.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <h6 class="card-title"><span class="bg-danger p-1">BDT.{{product.price}}</span></h6>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <a href="#" class="btn btn-primary">Buy Now</a>
          <a href="#" class="btn btn-primary">Add to Cart</a>
        </div>
      </div>
    </div>
    {% endfor %}
          
</div>

templates/partials/js.html
{% load static %}

  <script src="{% static '3.3.1main.js' %}"></script>

  
  <script type="text/javascript">
    function filterValueCheck() {
      var filter_value_list=[];
      $("input:checkbox[name^='filter']").each(function () {
          if ($(this).is(":checked")) {
              console.log($(this).val())
              filter_value_list.push($(this).val());
          }
      });
      console.log(filter_value_list)
      return filter_value_list
    }

    $("input:checkbox").click(function () {
      const price_range = [$("#minPrice").val(), $("#maxPrice").val()]
      const filter_value_list = filterValueCheck()
      const category_id = $("#filterForm").attr("category-data");
      const url = $("#filterForm").attr("data-filter-url");
      $.ajax({
        url: url,
        data: {
          'price_range' : price_range,
          'filter_value_list':filter_value_list,
          'category_id': category_id
        },
        success: function (data) {
          $("#filter_result").html(data);
        }
    });
  });

  function priceRangeFilter() {
      const price_range = [$("#minPrice").val(), $("#maxPrice").val()]
      const filter_value_list = filterValueCheck()
      const category_id = $("#filterForm").attr("category-data");
      const url = $("#filterForm").attr("data-filter-url");
      $.ajax({
        url: url,
        data: {
          'price_range' : price_range,
          'filter_value_list':filter_value_list,
          'category_id': category_id
        },
        success: function (data) {
          $("#filter_result").html(data);
        }
    });
  }
  
</script>

templates/shop/category_products.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <img src="{{category.image.url}}" style="width: 100%; height: auto;">

    <div class="row">
      <div class="col-2 mt-5 p-2">
        <div class="bg-light p-3">
          <div>
            <h4>Price</h4>
            <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Minimum" value="{{min_price}}" id="minPrice">
              <span class="input-group-text">To</span>
              <input type="text" class="form-control" placeholder="Maximum" value="{{max_price}}" id="maxPrice">
              <span class="input-group-text"><button type="button" onclick="priceRangeFilter()" class="btn btn-danger">Go</button></span>
            </div>
            <hr>
          </div>

          {% for p_filter in product_filter %}
          <h4>{{p_filter.name}}</h4>
          {% for value in p_filter.generic_filter.all %}
          <div class="form-check" id="filterForm" category-data = "{{category.id}}" data-filter-url="{% url 'shop:ajax_load_search_and_filter' %}">
            <input class="form-check-input" name="filter[]" type="checkbox" value="{{value.id}}" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
              {{value.name}}
            </label>
          </div>
          {% endfor %}
          <hr>
          {% endfor %}
        </div>
      </div>
      
      <div class="col-10 mt-3 p-3" id="filter_result">
        <h1 class="p-2">{{category.name}} has {{count}} Products</h1>
        <div class="row row-cols-1 row-cols-md-4 g-4">

          {% for product in products %}
          <div class="col">
            <div class="card">
              <img src="{{product.image.url}}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <h6 class="card-title"><span class="bg-danger p-1">BDT.{{product.price}}</span></h6>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
                <a href="#" class="btn btn-primary">Add to Cart</a>
              </div>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>

    </div>
        
    {% include 'partials/css.html' %}
    {% include 'partials/js.html' %}

{% endblock content %}

templates/shop/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h2>Category List</h2>
        <table class="table mt-4">
            <thead>
              <tr>
                <th scope="col">Category</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                <tr>
                    <td>{{obj.name}}</td>
                    <td><a href="{% url 'shop:category_product' obj.id %}" type="button" class="btn btn-success">See Products..</a></td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
{% endblock content %}